# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-10-23 08:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='friends',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('user', models.CharField(max_length=20)),
                ('friendid', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=20)),
                ('sex', models.IntegerField(default=0)),
                ('avatar', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='social',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('father', models.IntegerField(default=0)),
                ('platform', models.IntegerField(default=0)),
                ('account', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='users',
            fields=[
                ('username', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=30)),
                ('friendnum', models.IntegerField(default=0)),
            ],
        ),
    ]
