# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-11 14:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friends',
            name='avatar',
            field=models.ImageField(blank=True, default='upload/tmp.jpg', null=True, upload_to='upload'),
        ),
    ]
