# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-12 03:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20171111_2219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friends',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='upload'),
        ),
    ]
