# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-12 03:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20171112_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friends',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
