# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-14 09:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_auto_20171112_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friends',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='social',
            name='account',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.CharField(max_length=40),
        ),
    ]
