# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-14 15:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_auto_20171114_1734'),
    ]

    operations = [
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.IntegerField(default=0)),
                ('image', models.ImageField(upload_to='goods_photo')),
            ],
        ),
    ]
