# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-06 06:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_auto_20171114_2327'),
    ]

    operations = [
        migrations.CreateModel(
            name='allactivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('father', models.IntegerField(default=0)),
                ('username', models.CharField(max_length=30)),
                ('avatar_url', models.CharField(max_length=300)),
                ('headline', models.TextField()),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('actionType', models.TextField()),
                ('summary', models.TextField()),
                ('targetText', models.TextField()),
                ('source_url', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='focus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('father', models.IntegerField(default=0)),
                ('platform', models.IntegerField(default=0)),
                ('account', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='pics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('father', models.IntegerField(default=0)),
                ('imgs', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('father', models.IntegerField(default=0)),
                ('topics', models.CharField(max_length=300)),
            ],
        ),
        migrations.AddField(
            model_name='social',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
