# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-10 07:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_auto_20171206_1432'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='focus',
            name='account',
        ),
        migrations.RemoveField(
            model_name='focus',
            name='platform',
        ),
        migrations.AddField(
            model_name='focus',
            name='tag',
            field=models.CharField(default='软件工程', max_length=300),
        ),
        migrations.AlterField(
            model_name='focus',
            name='father',
            field=models.CharField(max_length=300),
        ),
    ]
