# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-11 10:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_auto_20171210_1525'),
    ]

    operations = [
        migrations.CreateModel(
            name='friendfriend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('father', models.IntegerField(default=0)),
                ('account', models.CharField(max_length=300)),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('loved', models.FloatField(default=0.0)),
                ('love', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='friendtopic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('father', models.IntegerField(default=0)),
                ('topics', models.CharField(max_length=300)),
                ('pp', models.FloatField(default=0.0)),
            ],
        ),
    ]
