# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-13 03:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_auto_20171213_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allactivity',
            name='mid',
            field=models.BigIntegerField(default=-1),
        ),
    ]
