# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-13 03:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_auto_20171213_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allactivity',
            name='mid',
            field=models.CharField(default='?', max_length=300),
        ),
    ]
